import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SoundProvider } from "@/components/SoundProvider";
import SoundToggle from "@/components/SoundToggle";
import CommandPalette from "@/components/CommandPalette";
import WatchedHydrator from "@/components/WatchedHydrator";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The Marvelous Journey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <SoundProvider>
          <div className="fixed right-4 top-4 z-50">
            <SoundToggle />
          </div>
          <WatchedHydrator />
          {children}
          <CommandPalette />
        </SoundProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
